# --- Font ---
font_family      IBM Plex Mono
bold_font        IBM Plex Mono Bold
bold_italic_font IBM Plex Mono Bold Italic
font_size 16

# --- Softening the Rendering ---
# Legacy strategy often helps with that "vague" CRT feel 
# compared to the ultra-sharp modern rendering.
text_composition_strategy platform

# --- Spacing ---
# Increase the height slightly so the "glowing" letters 
# feel like they have room on the glass.
modify_font cell_height 115%

# --- Rest of your original settings ---
cursor_shape            block
cursor_blink_interval   0.5
# background              #1a1b1c
# foreground              #00ff00
background_opacity      0.85
dynamic_background_opacity    yes 
background_blur         1
hide_window_decorations yes
window_padding_width    10
confirm_os_window_close 0
shell_integration       no-cursor
detect_urls             yes
mouse_hide_wait         3.0

tab_bar_style           powerline
include theme.conf


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
