preload = /home/anubhav/Pictures/Walls/anime_street_art_pixel_purp.png

# NEW NESTED SYNTAX for 2026
wallpaper {
    monitor = HDMI-A-1
    path = /home/anubhav/Pictures/Walls/anime_street_art_pixel_purp.png
}

wallpaper {
    monitor = eDP-1
    path = /home/anubhav/Pictures/Walls/anime_street_art_pixel_purp.png
}

ipc = on
splash = false
